package deepseek

import "time"

const (
	maxTokens      = 2000
	defaultTimeout = 210 * time.Second

	resumeToJSONPrompt  = "По предоставленному резюме сформируй json в соответствии с примером: {\n  \"location\": \"Москва, м. Крылатское\",\n  \"citizenship\": \"Россия\",\n  \"relocation_willingness\": \"Не готов к переезду\",\n  \"business_trips_willingness\": \"Готов к командировкам\",\n  \"desired_position\": \"Аналитик\",\n  \"specializations\": [\"Бизнес-аналитик\"],\n  \"employment_types\": [\"полная занятость\", \"проектная работа\"],\n  \"work_schedules\": [\"полный день\", \"гибкий график\", \"удаленная работа\"],\n  \"max_commute_time\": \"не более часа\",\n  \"total_experience\": \"11 месяцев\",\n  \"work_places\": [\n    {\n      \"company\": \"ПАО СБЕРБАНК\",\n      \"position\": \"Бизнес-аналитик\",\n      \"period\": \"Октябрь 2024 — настоящее время\",\n      \"duration\": \"11 месяцев\",\n      \"responsibilities\": [\n        \"Выявление потребностей заказчика, моделирование бизнес-процессов\",\n        \"Прототипирование пользовательского интерфейса\",\n        \"Подготовка Т3 для команды разработки\",\n        \"Анализ и документирование требований\",\n        \"Работа с инструментами прототипирования: Miro, draw.io, whiteboard\",\n        \"Имплементация self-service no code платформы на Camunda\",\n        \"Создание документации в Confluence и Jira\",\n        \"Проведение тестирования и демонстраций решений\",\n        \"Проведение UX исследований\",\n        \"Описание as is / to be, use case, user story\"\n      ]\n    }\n  ],\n  \"education\": [\n    \"2025: МГУ, Москва, Бизнес-информатика\",\n    \"2019: МГТУ им. Баумана, Автоматизация\"\n  ],\n  \"courses\": [\n    \"2025: Школа бизнес анализа (Пульс), Сбербанк, Бизнес аналитик\"\n  ],\n  \"languages\": [\n    \"Русский (родной)\",\n    \"Английский (B1 - Средний)\"\n  ],\n  \"skills\": [\n    \"UX-исследования\",\n    \"AS IS/TO BE mapping\", \n    \"User Story\",\n    \"Use case\",\n    \"Анализ обратной связи\",\n    \"Анализ бизнес-процессов\",\n    \"BPMN\",\n    \"Управление ресурсами\",\n    \"Управление бэклогом\"\n  ],\n  \"has_car\": true,\n  \"license_category\": \"B\",\n  \"about\": \"Обо мне\"\n}.\n Резюме: %s"
	vacancyToJSONPrompt = "По предоставленному тексту сформируй json в соответствии с моделью: type Vacancy struct {\n\tStatus                string    `json:\"status\"`\n\tName                  string    `json:\"name\"`\n\tRegion                string    `json:\"region\"`\n\tCity                  string    `json:\"city\"`\n\tAddress               string    `json:\"address\"`\n\tWorkType              string    `json:\"work_type\"`\n\tContractType          string    `json:\"contract_type\"`\n\tEmploymentType        string    `json:\"employment_type\"`\n\tWorkSchedule          string    `json:\"work_schedule\"`\n\tIncome                *int      `json:\"income,omitempty\"`\n\tSalaryMax             *int      `json:\"salary_max,omitempty\"`\n\tSalaryMin             *int      `json:\"salary_min,omitempty\"`\n\tPronounces            string    `json:\"pronounces\"`\n\tResponsibilities      string    `json:\"responsibilities\"`\n\tRequirements          string    `json:\"requirements\"`\n\tEducation             string    `json:\"education\"`\n\tExperience            string    `json:\"experience\"`\n\tSpecialPrograms       *bool     `json:\"special_programs,omitempty\"`\n\tComputerSkills        *bool     `json:\"computer_skills,omitempty\"`\n\tForeignLanguages      *bool     `json:\"foreign_languages,omitempty\"`\n\tLanguageLevel         *string   `json:\"language_level,omitempty\"`\n\tHasBusinessTrips      *bool     `json:\"has_business_trips,omitempty\"`\n\tAdditionalInformation *string   `json:\"additional_information,omitempty\"`\n}\n. Текст: %s"
	interviewPlanPrompt = "Тебе представлен объект вакансии, для него составь план собеседования который позволит проверить все требования вакансии, hard и soft skills соискателя, напиши список тем о которых нужно спросить сискателя в формате: тема1, тема2 и так далее. Ответ должен содержать только названия тем через запятую не пиши лишний текст убери все описания тем. Вакансия: %s"
	dialogPrompt        = "Ты профессиональный hr менеджер тебе представлен план собеседования и начатый другим hr менеджером диалог с соискателем напиши фразу которую ты бы ответил соискателю в ответ, если необходимо задавай вопросы по текущей теме либо переходи к следующей, если на текущую тему из плана уже задано 3 или более вопроса переходи к следующей теме. План: %s, Текущий диалог: %s"
)
